rules:
    border-zero: 2
    brace-style: 2
    class-name-format: 2
    clean-import-paths: 2
    empty-args: 2
    empty-line-between-blocks: 2
    extends-before-declarations: 2
    extends-before-mixins: 2
    final-newline: 2
    force-attribute-nesting: 2
    force-element-nesting: 0
    force-pseudo-nesting: 0
    hex-length: 2
    hex-notation: 2
    indentation:
        - 2
        - size: 4
    leading-zero: 2
    mixins-before-declarations: 2
    property-sort-order:
        - 2
        - order: smacss
    no-color-literals: 2
    no-css-comments: 2
    no-duplicate-properties: 2
    no-ids: 0
    no-mergeable-selectors: 2
    no-trailing-whitespace: 2
    no-trailing-zero: 2
    no-transition-all: 2
    no-url-domains: 0
    no-url-protocols:
        - 2
        - allow-protocol-relative-urls: true
    no-vendor-prefixes: 0
    one-declaration-per-line: 2
    pseudo-element: 0
    quotes: 2
    shorthand-values: 2
    single-line-per-selector: 0
    space-after-colon: 2
    space-after-comma: 2
    space-before-brace: 2
    trailing-semicolon: 2
    url-quotes: 2
    variable-name-format: 2
    zero-unit: 2
